#pragma once

#include <Script/ScriptEnum.h>
#include <Script/effect/gs_effect.h>
#include <Script/effect/gs_effectsystem.h>
#include <Script/gs_entity.h>
#include <Script/gs_gui.h>
#include <Script/gs_gui2.h>
#include <Script/gs_info.h>
#include <Script/gs_music.h>
#include <Script/gs_scriptargs.h>
#include <Script/gs_scriptmacros.h>
#include <Script/gs_template.h>
#include <Script/gs_world.h>
#include <Script/propertyset/gs_propertymacros.h>
#include <Script/propertyset/gs_psaizone.h>
#include <Script/propertyset/gs_psanchor.h>
#include <Script/propertyset/gs_psanimation.h>
#include <Script/propertyset/gs_psarena.h>
#include <Script/propertyset/gs_psbook.h>
#include <Script/propertyset/gs_pscamera.h>
#include <Script/propertyset/gs_pscharactercontrol.h>
#include <Script/propertyset/gs_pscharactermovement.h>
#include <Script/propertyset/gs_psclock.h>
#include <Script/propertyset/gs_pscollisionshape.h>
#include <Script/propertyset/gs_psdamage.h>
#include <Script/propertyset/gs_psdamagereceiver.h>
#include <Script/propertyset/gs_psdialog.h>
#include <Script/propertyset/gs_psdoor.h>
#include <Script/propertyset/gs_pseffect.h>
#include <Script/propertyset/gs_psenclave.h>
#include <Script/propertyset/gs_psfocus.h>
#include <Script/propertyset/gs_psinfomanager.h>
#include <Script/propertyset/gs_psinfoscriptcommand.h>
#include <Script/propertyset/gs_psinteraction.h>
#include <Script/propertyset/gs_psinventory.h>
#include <Script/propertyset/gs_psitem.h>
#include <Script/propertyset/gs_psitemwrapper.h>
#include <Script/propertyset/gs_psletter.h>
#include <Script/propertyset/gs_pslock.h>
#include <Script/propertyset/gs_psmagic.h>
#include <Script/propertyset/gs_psmap.h>
#include <Script/propertyset/gs_psmover.h>
#include <Script/propertyset/gs_psnavigation.h>
#include <Script/propertyset/gs_psnpc.h>
#include <Script/propertyset/gs_psparticle.h>
#include <Script/propertyset/gs_psparty.h>
#include <Script/propertyset/gs_psplayermemory.h>
#include <Script/propertyset/gs_psprojectile.h>
#include <Script/propertyset/gs_psquestmanager.h>
#include <Script/propertyset/gs_psrecipe.h>
#include <Script/propertyset/gs_psrigidbody.h>
#include <Script/propertyset/gs_psroutine.h>
#include <Script/propertyset/gs_psskill.h>
#include <Script/propertyset/gs_psstatistics.h>
#include <Script/propertyset/gs_psstrip.h>
#include <Script/propertyset/gs_pstouchdamage.h>
#include <Script/propertyset/gs_pstreasureset.h>
#include <Script/propertyset/gs_pstrigger.h>
