#pragma once

#include <SharedBase/SharedBaseEnum.h>
#include <SharedBase/animation/ge_interpolatorbase.h>
#include <SharedBase/animation/ge_motionkeyframerdata.h>
#include <SharedBase/color/ge_bytealphacolor.h>
#include <SharedBase/color/ge_bytecolor.h>
#include <SharedBase/color/ge_colorbase.h>
#include <SharedBase/color/ge_floatalphacolor.h>
#include <SharedBase/color/ge_floatcolor.h>
#include <SharedBase/color/ge_floatcolorhsv.h>
#include <SharedBase/container/array/ge_arraybase.h>
#include <SharedBase/container/array/ge_autoptrarray.h>
#include <SharedBase/container/array/ge_objarray.h>
#include <SharedBase/container/array/ge_objarraysort.h>
#include <SharedBase/container/array/ge_ptrarray.h>
#include <SharedBase/container/array/ge_ptrarraysort.h>
#include <SharedBase/container/array/ge_smallarray.h>
#include <SharedBase/container/array/ge_valarray.h>
#include <SharedBase/container/ge_bitfield.h>
#include <SharedBase/container/ge_trackbitfield.h>
#include <SharedBase/container/map/ge_mapbase.h>
#include <SharedBase/container/map/ge_objmap.h>
#include <SharedBase/container/map/ge_ptrmap.h>
#include <SharedBase/container/map/ge_stringmap.h>
#include <SharedBase/container/map/ge_valmap.h>
#include <SharedBase/container/set/ge_set.h>
#include <SharedBase/container/stack/ge_objstack.h>
#include <SharedBase/io/ge_commandline.h>
#include <SharedBase/io/ge_file.h>
#include <SharedBase/io/ge_filesystem.h>
#include <SharedBase/io/streams/ge_iostream.h>
#include <SharedBase/io/streams/ge_istream.h>
#include <SharedBase/io/streams/ge_memorystream.h>
#include <SharedBase/io/streams/ge_nullstream.h>
#include <SharedBase/io/streams/ge_ostream.h>
#include <SharedBase/io/streams/ge_postream.h>
#include <SharedBase/io/streams/ge_streamutil.h>
#include <SharedBase/kernel/error/ge_erroradmin.h>
#include <SharedBase/kernel/error/ge_gothic3enginedialogs.h>
#include <SharedBase/kernel/event/ge_event.h>
#include <SharedBase/kernel/event/ge_eventwin32.h>
#include <SharedBase/kernel/layout/ge_classlayout.h>
#include <SharedBase/kernel/layout/ge_setlayout.h>
#include <SharedBase/kernel/memory/ge_memheap.h>
#include <SharedBase/kernel/memory/ge_memoryadmin.h>
#include <SharedBase/kernel/memory/ge_validatememory.h>
#include <SharedBase/kernel/message/ge_messageadmin.h>
#include <SharedBase/kernel/object/ge_classname.h>
#include <SharedBase/kernel/object/ge_classnamebase.h>
#include <SharedBase/kernel/object/ge_objectbase.h>
#include <SharedBase/kernel/object/ge_objectrefbase.h>
#include <SharedBase/kernel/object/ge_obsoleteclass.h>
#include <SharedBase/kernel/system/ge_clock.h>
#include <SharedBase/kernel/system/ge_datetime.h>
#include <SharedBase/kernel/system/ge_fpuadmin.h>
#include <SharedBase/kernel/system/ge_timer.h>
#include <SharedBase/kernel/thread/ge_criticalsectionwin32.h>
#include <SharedBase/kernel/thread/ge_multireadexclusivewritewin32.h>
#include <SharedBase/kernel/thread/ge_spieadmin.h>
#include <SharedBase/kernel/thread/ge_spyadmin.h>
#include <SharedBase/kernel/thread/ge_threadobjectrefbase.h>
#include <SharedBase/kernel/thread/ge_threadwin32.h>
#include <SharedBase/kernel/thread/ge_threadwin32ex.h>
#include <SharedBase/math/2d/ge_matrix2.h>
#include <SharedBase/math/2d/ge_point.h>
#include <SharedBase/math/2d/ge_rect.h>
#include <SharedBase/math/2d/ge_vector2.h>
#include <SharedBase/math/2d/ge_zoneraster.h>
#include <SharedBase/math/3d/ge_axisangle.h>
#include <SharedBase/math/3d/ge_eigenvector.h>
#include <SharedBase/math/3d/ge_eulerangles.h>
#include <SharedBase/math/3d/ge_matrix.h>
#include <SharedBase/math/3d/ge_matrix3.h>
#include <SharedBase/math/3d/ge_motion.h>
#include <SharedBase/math/3d/ge_octtree.h>
#include <SharedBase/math/3d/ge_point3.h>
#include <SharedBase/math/3d/ge_quaternion.h>
#include <SharedBase/math/3d/ge_sphericalrotation.h>
#include <SharedBase/math/3d/ge_vector.h>
#include <SharedBase/math/3d/ge_vector4.h>
#include <SharedBase/math/3d/geometry/ge_box.h>
#include <SharedBase/math/3d/geometry/ge_capsule.h>
#include <SharedBase/math/3d/geometry/ge_frustum.h>
#include <SharedBase/math/3d/geometry/ge_infcylinder.h>
#include <SharedBase/math/3d/geometry/ge_infdoublecylinder.h>
#include <SharedBase/math/3d/geometry/ge_line.h>
#include <SharedBase/math/3d/geometry/ge_orientedbox.h>
#include <SharedBase/math/3d/geometry/ge_plane.h>
#include <SharedBase/math/3d/geometry/ge_ray.h>
#include <SharedBase/math/3d/geometry/ge_sphere.h>
#include <SharedBase/math/3d/geometry/ge_stretch.h>
#include <SharedBase/math/3d/geometry/ge_triangle.h>
#include <SharedBase/math/3d/geometry/ge_unitedray.h>
#include <SharedBase/math/3d/geometry/ge_volume.h>
#include <SharedBase/math/ge_flexiblevertexformat.h>
#include <SharedBase/math/ge_flexiblevertexptr.h>
#include <SharedBase/math/ge_md5.h>
#include <SharedBase/math/ge_random.h>
#include <SharedBase/math/noise/ge_ebertnoise.h>
#include <SharedBase/math/noise/ge_noise.h>
#include <SharedBase/math/noise/ge_peacheynoise.h>
#include <SharedBase/math/noise/ge_perlinnoise.h>
#include <SharedBase/math/range/ge_range1.h>
#include <SharedBase/math/range/ge_range2.h>
#include <SharedBase/math/range/ge_range3.h>
#include <SharedBase/math/range/ge_range4.h>
#include <SharedBase/propertysystem/acessors/ge_accessorcreator.h>
#include <SharedBase/propertysystem/acessors/ge_accessorenum.h>
#include <SharedBase/propertysystem/acessors/ge_accessorproperty.h>
#include <SharedBase/propertysystem/acessors/ge_accessorpropertyobject.h>
#include <SharedBase/propertysystem/base/ge_auto_po_smartptr.h>
#include <SharedBase/propertysystem/base/ge_po_puresmartptr.h>
#include <SharedBase/propertysystem/base/ge_po_smartptr.h>
#include <SharedBase/propertysystem/base/ge_propertyid.h>
#include <SharedBase/propertysystem/enum/ge_enumwrapper.h>
#include <SharedBase/propertysystem/enum/ge_propertycontainer.h>
#include <SharedBase/propertysystem/factories/ge_propertyobjectfactory.h>
#include <SharedBase/propertysystem/factories/ge_propertyobjectsingleton.h>
#include <SharedBase/propertysystem/ge_propertymacros.h>
#include <SharedBase/propertysystem/objects/ge_propertyobject.h>
#include <SharedBase/propertysystem/objects/ge_propertyobjectbase.h>
#include <SharedBase/propertysystem/objects/ge_propertyobjecttype.h>
#include <SharedBase/propertysystem/objects/ge_propertyobjecttypebase.h>
#include <SharedBase/propertysystem/persistence/ge_propertylayout.h>
#include <SharedBase/propertysystem/types/ge_propertytype.h>
#include <SharedBase/propertysystem/types/ge_propertytypebase.h>
#include <SharedBase/propertysystem/types/ge_propertytypeonly.h>
#include <SharedBase/types/ge_def.h>
#include <SharedBase/types/ge_delegatebase.h>
#include <SharedBase/types/ge_globals.h>
#include <SharedBase/types/ge_guid.h>
#include <SharedBase/types/ge_string.h>
#include <SharedBase/types/ge_stringconverter.h>
#include <SharedBase/types/ge_types.h>
#include <SharedBase/types/ge_unicodestring.h>
#include <SharedBase/types/ge_unknown.h>
#include <SharedBase/types/ge_variant.h>
#include <SharedBase/types/ge_windows.h>
