#ifndef SCRIPTENUM_H_INCLUDED
#define SCRIPTENUM_H_INCLUDED

enum ECommand {
    ECommand_Say                  = 0,
    ECommand_SaySVM               = 1,
    ECommand_SaySound             = 2,
    ECommand_SayKeepItUp          = 3,
    ECommand_SayBossNews          = 4,
    ECommand_SayGuardNews         = 5,
    ECommand_SayConfirm           = 6,
    ECommand_SayHoldingPosition   = 7,
    ECommand_Excuse               = 8,
    ECommand_Bribe                = 9,
    ECommand_PickPocket           = 10,
    ECommand_Attack               = 11,
    ECommand_GiveXP               = 12,
    ECommand_Give                 = 13,
    ECommand_Wear                 = 14,
    ECommand_Use                  = 15,
    ECommand_Heal                 = 16,
    ECommand_OpenDoor             = 17,
    ECommand_SetClass             = 18,
    ECommand_SetPAL               = 19,
    ECommand_SetEnclave           = 20,
    ECommand_Sleep                = 21,
    ECommand_SetTeachEnabled      = 22,
    ECommand_SetTradeEnabled      = 23,
    ECommand_SetPartyEnabled      = 24,
    ECommand_SetMobEnabled        = 25,
    ECommand_SetSlaveryEnabled    = 26,
    ECommand_SetRevolutionEnabled = 27,
    ECommand_SetRaidEnabled       = 28,
    ECommand_SetSleepingPoint     = 29,
    ECommand_SetWorkingPoint      = 30,
    ECommand_SetRelaxingPoint     = 31,
    ECommand_FullStop             = 32,
    ECommand_SetRoutine           = 33,
    ECommand_SetGuardStatus       = 34,
    ECommand_SetGameEvent         = 35,
    ECommand_ClearGameEvent       = 36,
    ECommand_MoveTo               = 37,
    ECommand_SetSectorStatus      = 38,
    ECommand_RunQuest             = 39,
    ECommand_CloseQuest           = 40,
    ECommand_SucceedQuest         = 41,
    ECommand_StartEffect          = 42,
    ECommand_DoTrade              = 43,
    ECommand_DoLoot               = 44,
    ECommand_ShowPicture          = 45,
    ECommand_ShowSubtitle         = 46,
    ECommand_PlayMusic_NI         = 47,
    ECommand_InfoWait             = 48,
    ECommand_EndGame              = 49,
    ECommand_Back_NI              = 50,
    ECommand_End                  = 51,
    ECommand_BoostAttribs         = 52,
    ECommand_SetChapter           = 53,
    ECommand_Erase                = 54,
    ECommand_StartRevolution      = 55,
    ECommand_Spawn                = 56,
    ECommand_ShowGameMessage      = 57,
    ECommand_AddQuestLog          = 58,
    ECommand_ModReputPol          = 59,
    ECommand_ModReputEnc          = 60,
    ECommand_Grant                = 61,
    ECommand_Humanize             = 62,
    ECommand_JoinNPC              = 63,
    ECommand_GiveAll              = 64,
    ECommand_JoinPlayer           = 65,
    ECommand_FailQuest            = 66,
    ECommand_ResetCrime           = 67,
    ECommand_DecreaseRevolCount   = 68
};

enum EDifficulty {
    EDifficulty_Easy   = 0,
    EDifficulty_Medium = 1,
    EDifficulty_Hard = 2
};

#endif
