#pragma once

#include "Script.h"
#include "Util.h"

#define ME_SCRIPT_WRAPPER( NAME ) ME_SCRIPT_WRAPPER_RA( GEInt, NAME, GEInt )
#define ME_SCRIPT_WRAPPER_A( NAME, ARG_TYPE ) ME_SCRIPT_WRAPPER_RA( GEInt, NAME, ARG_TYPE )
#define ME_SCRIPT_WRAPPER_R( RET_TYPE, NAME ) ME_SCRIPT_WRAPPER_RA( RET_TYPE, NAME, GEInt )
#define ME_SCRIPT_WRAPPER_RA( RET_TYPE, NAME, ARG_TYPE ) \
    RET_TYPE inline NAME ( Entity & a_pSelfEntity, Entity & a_pOtherEntity = None, ARG_TYPE a_iArgs = static_cast<ARG_TYPE>(0) ) \
    { \
        return static_cast<RET_TYPE>(FindModule<gCScriptAdmin>()->CallScriptFromScript(#NAME, &a_pSelfEntity, &a_pOtherEntity, static_cast<GEInt>(a_iArgs))); \
    }

#define ME_SCRIPT_WRAPPER_B( NAME ) ME_SCRIPT_WRAPPER_BA( NAME, GEInt )
#define ME_SCRIPT_WRAPPER_BA( NAME, ARG_TYPE ) \
    GEBool inline NAME ( Entity & a_pSelfEntity, Entity & a_pOtherEntity = None, ARG_TYPE a_iArgs = static_cast<ARG_TYPE>(0) ) \
    { \
        return FindModule<gCScriptAdmin>()->CallScriptFromScript(#NAME, &a_pSelfEntity, &a_pOtherEntity, static_cast<GEInt>(a_iArgs)) == 1; \
    }


namespace AI_Decision
{
    ME_SCRIPT_WRAPPER_B( CanParade )
    ME_SCRIPT_WRAPPER_B( CanParadeMoveOf )
    ME_SCRIPT_WRAPPER_B( IsInParadeMode )
    ME_SCRIPT_WRAPPER_B( IsInParadePose )
    ME_SCRIPT_WRAPPER_B( IsInFistMode )
    ME_SCRIPT_WRAPPER_B( HasStaffMagicParade )
    ME_SCRIPT_WRAPPER_B( CanParadeMagic )
    ME_SCRIPT_WRAPPER_B( CanParadeMissile )
    ME_SCRIPT_WRAPPER_B( CanSleep )
    ME_SCRIPT_WRAPPER_B( CanThreaten )
    ME_SCRIPT_WRAPPER_B( CanEatGround )
    ME_SCRIPT_WRAPPER_B( CanSwim )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetAttitude )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetOutlawAttitude )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetRevolutionAttitude )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetAttitudeToPlayer )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetFocusNameAttitude )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetZoneAttitudeToPlayer )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetPoliticalAttitude )
    ME_SCRIPT_WRAPPER_R( gEAttitude, GetSpeciesAttitude )
    ME_SCRIPT_WRAPPER_B( IsAmbientCreature )
    ME_SCRIPT_WRAPPER( GetFollowTime )
    ME_SCRIPT_WRAPPER_B( HasAttackReasonToKill )
    ME_SCRIPT_WRAPPER_B( HasAttackReasonToWatch )
    ME_SCRIPT_WRAPPER_B( HasDangerousWeapon )
    ME_SCRIPT_WRAPPER_B( IsDroppableWeapon )
    ME_SCRIPT_WRAPPER_B( IsEvil )
    ME_SCRIPT_WRAPPER_B( IsBoss )
    ME_SCRIPT_WRAPPER_B( IsGuard )
    ME_SCRIPT_WRAPPER_B( IsGateGuard )
    ME_SCRIPT_WRAPPER_B( IsHumanoid )
    ME_SCRIPT_WRAPPER_B( IsLivestock )
    ME_SCRIPT_WRAPPER_B( IsSlave )
    ME_SCRIPT_WRAPPER_B( IsUndead )
    ME_SCRIPT_WRAPPER( SetLastFightTimestamp )
    ME_SCRIPT_WRAPPER_B( IsTemporaryFriendlyToPlayer )
    ME_SCRIPT_WRAPPER_B( IsUpset )
    ME_SCRIPT_WRAPPER_B( WantToEat )
    ME_SCRIPT_WRAPPER_B( WantToFlee )
    ME_SCRIPT_WRAPPER_B( WantToRansack )
}

namespace AI_Tasks
{
    ME_SCRIPT_WRAPPER( OnAttack )
    ME_SCRIPT_WRAPPER( CancelAttack )
    ME_SCRIPT_WRAPPER( GetCombatWalkMode )
    ME_SCRIPT_WRAPPER( Kill )
    ME_SCRIPT_WRAPPER( CleanUpPlunderInv )
    ME_SCRIPT_WRAPPER( PipiStumble )
    ME_SCRIPT_WRAPPER( AssessAgressor )
    ME_SCRIPT_WRAPPER( ResetAll )
    ME_SCRIPT_WRAPPER( ResetInteraction )
    ME_SCRIPT_WRAPPER( DropHandItems )
    ME_SCRIPT_WRAPPER( RemoveNonCombatItems )
    ME_SCRIPT_WRAPPER( Defeat )
    ME_SCRIPT_WRAPPER( CheerFight )
}

namespace AI_Perception
{
    ME_SCRIPT_WRAPPER( AssessActivePerception )
    ME_SCRIPT_WRAPPER( AssessCmdAttack )
    ME_SCRIPT_WRAPPER( AssessCmdFollow )
    ME_SCRIPT_WRAPPER( AssessDefeat )
    ME_SCRIPT_WRAPPER( AssessFightSound )
    ME_SCRIPT_WRAPPER( AssessHit )
    ME_SCRIPT_WRAPPER_BA( CanBePoisoned, GEBool )
    ME_SCRIPT_WRAPPER_B( CanBeDiseased )
    ME_SCRIPT_WRAPPER_B( CanBurn )
    ME_SCRIPT_WRAPPER_B( CanFreeze )
    ME_SCRIPT_WRAPPER_B( CanBeKilled )
    ME_SCRIPT_WRAPPER_B( IsDeadlyDamage )
    ME_SCRIPT_WRAPPER( GetProtection )
    ME_SCRIPT_WRAPPER( GetPlayerSkillDamageBonus )
    ME_SCRIPT_WRAPPER( GetProtectionForHUD )
    ME_SCRIPT_WRAPPER( AssessMurder )
    ME_SCRIPT_WRAPPER( AssessPlayer )
    ME_SCRIPT_WRAPPER( AssessPlayerSneaking )
    ME_SCRIPT_WRAPPER( AssessPlayerWeapon )
    ME_SCRIPT_WRAPPER( AssessPlayerZone )
    ME_SCRIPT_WRAPPER( AssessPlayerEnterZone )
    ME_SCRIPT_WRAPPER( AssessPrey )
    ME_SCRIPT_WRAPPER( AssessTakeItem )
    ME_SCRIPT_WRAPPER_B( IsBotheredByPlayerTheftOf )
    ME_SCRIPT_WRAPPER( AssessTalk )
    ME_SCRIPT_WRAPPER_BA( AssessTarget, gEAttackReason )
    ME_SCRIPT_WRAPPER( AssessUseInteractObject )
    ME_SCRIPT_WRAPPER( AssessWarn )
    ME_SCRIPT_WRAPPER( AssessAttack )
    ME_SCRIPT_WRAPPER_B( CanReceivePerceptionFrom )
    ME_SCRIPT_WRAPPER( SendPerceptionCmdAttack )
    ME_SCRIPT_WRAPPER( SendPerceptionCmdFollow )
    ME_SCRIPT_WRAPPER( SendPerceptionFightSound )
    ME_SCRIPT_WRAPPER( SendPerceptionDefeat )
    ME_SCRIPT_WRAPPER( SendPerceptionMurder )
    ME_SCRIPT_WRAPPER( SendPerceptionTakeItem )
    ME_SCRIPT_WRAPPER( SendPerceptionUseInteractObject )
    ME_SCRIPT_WRAPPER( SendPerceptionWarn )
    ME_SCRIPT_WRAPPER( SendPerceptionPreach )
    ME_SCRIPT_WRAPPER( SendPerceptionEnterZone )
    ME_SCRIPT_WRAPPER( CallHelp )
}

namespace AI_Memory
{
    ME_SCRIPT_WRAPPER( GetStrength )
    ME_SCRIPT_WRAPPER( GetDexterity )
    ME_SCRIPT_WRAPPER( GetIntelligence )
    ME_SCRIPT_WRAPPER( GetAlchemy )
    ME_SCRIPT_WRAPPER( GetSmithing )
    ME_SCRIPT_WRAPPER( GetTheft )
    ME_SCRIPT_WRAPPER( SetStrength )
    ME_SCRIPT_WRAPPER( SetDexterity )
    ME_SCRIPT_WRAPPER( SetIntelligence )
    ME_SCRIPT_WRAPPER( SetAlchemy )
    ME_SCRIPT_WRAPPER( SetSmithing )
    ME_SCRIPT_WRAPPER( SetTheft )
    ME_SCRIPT_WRAPPER( AddStrength )
    ME_SCRIPT_WRAPPER( AddDexterity )
    ME_SCRIPT_WRAPPER( AddIntelligence )
    ME_SCRIPT_WRAPPER( AddAlchemy )
    ME_SCRIPT_WRAPPER( AddSmithing )
    ME_SCRIPT_WRAPPER( AddTheft )
    ME_SCRIPT_WRAPPER( GetProtectionBlade )
    ME_SCRIPT_WRAPPER( GetProtectionImpact )
    ME_SCRIPT_WRAPPER( GetProtectionMissile )
    ME_SCRIPT_WRAPPER( GetProtectionFire )
    ME_SCRIPT_WRAPPER( GetProtectionIce )
    ME_SCRIPT_WRAPPER( GetProtectionLightning )
    ME_SCRIPT_WRAPPER( SetProtectionBlades )
    ME_SCRIPT_WRAPPER( SetProtectionImpact )
    ME_SCRIPT_WRAPPER( SetProtectionMissile )
    ME_SCRIPT_WRAPPER( SetProtectionFire )
    ME_SCRIPT_WRAPPER( SetProtectionIce )
    ME_SCRIPT_WRAPPER( SetProtectionLightning )
    ME_SCRIPT_WRAPPER( AddProtectionBlades )
    ME_SCRIPT_WRAPPER( AddProtectionImpact )
    ME_SCRIPT_WRAPPER( AddProtectionMissile )
    ME_SCRIPT_WRAPPER( AddProtectionFire )
    ME_SCRIPT_WRAPPER( AddProtectionIce )
    ME_SCRIPT_WRAPPER( AddProtectionLightning )
    ME_SCRIPT_WRAPPER( GetHitPoints )
    ME_SCRIPT_WRAPPER( GetHitPointsMax )
    ME_SCRIPT_WRAPPER( GetHitPointsPercent )
    ME_SCRIPT_WRAPPER( SetHitPoints )
    ME_SCRIPT_WRAPPER( SetHitPointsMax )
    ME_SCRIPT_WRAPPER( AddHitPoints )
    ME_SCRIPT_WRAPPER( AddHitPointsMax )
    ME_SCRIPT_WRAPPER( GetManaPoints )
    ME_SCRIPT_WRAPPER( GetManaPointsMax )
    ME_SCRIPT_WRAPPER( GetManaPointsPercent )
    ME_SCRIPT_WRAPPER( SetManaPoints )
    ME_SCRIPT_WRAPPER( SetManaPointsMax )
    ME_SCRIPT_WRAPPER( AddManaPoints )
    ME_SCRIPT_WRAPPER( AddManaPointsMax )
    ME_SCRIPT_WRAPPER( GetStaminaPoints )
    ME_SCRIPT_WRAPPER( GetStaminaPointsMax )
    ME_SCRIPT_WRAPPER( GetStaminaPointsPercent )
    ME_SCRIPT_WRAPPER( SetStaminaPoints )
    ME_SCRIPT_WRAPPER( SetStaminaPointsMax )
    ME_SCRIPT_WRAPPER( AddStaminaPoints )
    ME_SCRIPT_WRAPPER( AddStaminaPointsMax )
    ME_SCRIPT_WRAPPER( GetCurrentLevel )
    ME_SCRIPT_WRAPPER( GetLevel )
    ME_SCRIPT_WRAPPER( GetLevelMax )
    ME_SCRIPT_WRAPPER( GetDiffToPlayerLevel )
    ME_SCRIPT_WRAPPER( GetPlayerCrime )
    ME_SCRIPT_WRAPPER( MemorizePlayerCrime )
    ME_SCRIPT_WRAPPER( SetAttackReason )
}

namespace AI_Commands
{
    ME_SCRIPT_WRAPPER_B( IsInteractAction )
    ME_SCRIPT_WRAPPER_B( IsInteractAniStateAction )
    ME_SCRIPT_WRAPPER_R( gEAttackReason, GetGuardAttackReason )
    ME_SCRIPT_WRAPPER( PickPocket )
    ME_SCRIPT_WRAPPER( GeneratePickpocketInventory )
    ME_SCRIPT_WRAPPER( EndGoto )
    ME_SCRIPT_WRAPPER( HandleControlledReturnHome )
    ME_SCRIPT_WRAPPER( GiveXP )
    ME_SCRIPT_WRAPPER( GetXPNext )
    ME_SCRIPT_WRAPPER( GetAttackRange )
    ME_SCRIPT_WRAPPER( GetCloseRange )
    ME_SCRIPT_WRAPPER( SelectCombatMove )
    ME_SCRIPT_WRAPPER( FAI_Active )
    ME_SCRIPT_WRAPPER( FAI_Passive )
    ME_SCRIPT_WRAPPER( FAI_Ranged )
    ME_SCRIPT_WRAPPER( FAI_Magic )
    ME_SCRIPT_WRAPPER( FAI_Misted )
    ME_SCRIPT_WRAPPER( StartSayAttackEnd )
    ME_SCRIPT_WRAPPER( StartSayDefeatComment )
    ME_SCRIPT_WRAPPER( StartSayAttackReason )
    ME_SCRIPT_WRAPPER( StartSayConfirm )
    ME_SCRIPT_WRAPPER( StartSayHoldingPosition )
    ME_SCRIPT_WRAPPER( StartSayFollow )
    ME_SCRIPT_WRAPPER( StartSayRefuseTalk )
    ME_SCRIPT_WRAPPER( StartSayCrimeRefuse )
    ME_SCRIPT_WRAPPER( StartSayZoneRefuse )
    ME_SCRIPT_WRAPPER( StartSayAargh )
}

namespace Magic_Spells
{
    ME_SCRIPT_WRAPPER( GetCastAction )
    ME_SCRIPT_WRAPPER( MagicInstant )
    ME_SCRIPT_WRAPPER( MagicProjectile )
    ME_SCRIPT_WRAPPER( MagicSummon )
    ME_SCRIPT_WRAPPER( MagicDispel )
    ME_SCRIPT_WRAPPER( MagicHeatWave )
    ME_SCRIPT_WRAPPER( MagicFrostWave )
    ME_SCRIPT_WRAPPER( MagicShockWave )
    ME_SCRIPT_WRAPPER( MagicCure )
    ME_SCRIPT_WRAPPER( MagicCurePoison )
    ME_SCRIPT_WRAPPER( MagicCureDisease )
    ME_SCRIPT_WRAPPER( MagicAnimalForm )
    ME_SCRIPT_WRAPPER( SendPerceptionTransform )
    ME_SCRIPT_WRAPPER( MagicCallAnimals )
    ME_SCRIPT_WRAPPER( MagicHypnosis )
    ME_SCRIPT_WRAPPER( MagicSleep )
    ME_SCRIPT_WRAPPER_B( CanControl )
    ME_SCRIPT_WRAPPER( MagicWordOfControl )
    ME_SCRIPT_WRAPPER( MagicTameAnimal )
    ME_SCRIPT_WRAPPER( MagicSummonDemon )
    ME_SCRIPT_WRAPPER( MagicSummonSkeleton )
    ME_SCRIPT_WRAPPER( MagicSummonGolem )
    ME_SCRIPT_WRAPPER( MagicSummonGoblin )
    ME_SCRIPT_WRAPPER( MagicSummonArmyOfDarkness )
    ME_SCRIPT_WRAPPER( MagicSummonMonster )
    ME_SCRIPT_WRAPPER( MagicSummonCompanion )
    ME_SCRIPT_WRAPPER( MagicSummonLightning )
    ME_SCRIPT_WRAPPER( MagicSummonMist )
    ME_SCRIPT_WRAPPER( MagicBloodlust )
    ME_SCRIPT_WRAPPER( MagicFear )
    ME_SCRIPT_WRAPPER( MagicTelekinesis )
    ME_SCRIPT_WRAPPER( MagicSoulTravel )
    ME_SCRIPT_WRAPPER( MagicTimeBubble )
    ME_SCRIPT_WRAPPER( MagicDuskToDawn )
    ME_SCRIPT_WRAPPER( MagicCharm )
    ME_SCRIPT_WRAPPER( MagicSummonArmyOfCuteness )
    ME_SCRIPT_WRAPPER( MagicBlessWeapon )
    ME_SCRIPT_WRAPPER( MagicHealOther )
    ME_SCRIPT_WRAPPER( MagicDestroyEvil )
    ME_SCRIPT_WRAPPER( MagicOpenLocks )
    ME_SCRIPT_WRAPPER( MagicMeteor )
    ME_SCRIPT_WRAPPER( MagicIceBomb )
    ME_SCRIPT_WRAPPER( MagicSummonFlameSword )
    ME_SCRIPT_WRAPPER( MagicBurn )
    ME_SCRIPT_WRAPPER( MagicFreeze )
    ME_SCRIPT_WRAPPER( MagicPoison )
    ME_SCRIPT_WRAPPER( MagicDisease )
    ME_SCRIPT_WRAPPER( MagicHeal )
    ME_SCRIPT_WRAPPER( MagicRefresh )
    ME_SCRIPT_WRAPPER( MagicTeleport )
    ME_SCRIPT_WRAPPER( MagicTransform )
    ME_SCRIPT_WRAPPER_B( IsAnimal )
    ME_SCRIPT_WRAPPER_B( CanAttack )
    ME_SCRIPT_WRAPPER_B( IsBig )
    ME_SCRIPT_WRAPPER_B( IsLarge )
    ME_SCRIPT_WRAPPER_B( IsGame )
    ME_SCRIPT_WRAPPER( GetPlayerSpellDurationBonus )
    ME_SCRIPT_WRAPPER( GetTransformDuration )
    ME_SCRIPT_WRAPPER( ReturnToBody )
    ME_SCRIPT_WRAPPER( TransformBack )
    ME_SCRIPT_WRAPPER( MagicSpeedUp )
    ME_SCRIPT_WRAPPER( MagicKeepStamina )
    ME_SCRIPT_WRAPPER( MagicStun )
}

namespace Magic_States
{
    ME_SCRIPT_WRAPPER( MagicAreaDamageTick )
    ME_SCRIPT_WRAPPER( MagicMistTick )
    ME_SCRIPT_WRAPPER( AssessMist )
    ME_SCRIPT_WRAPPER( MagicMistTickNoAggro )
    ME_SCRIPT_WRAPPER( AssessMistNoAggro )
}

namespace Magic_Decision
{
    ME_SCRIPT_WRAPPER_B( CanTameAnimal )
    ME_SCRIPT_WRAPPER_B( CanTransformInto )
}

namespace Magic_Barrier
{
    ME_SCRIPT_WRAPPER( OnEnterMagicBarrier )
    ME_SCRIPT_WRAPPER( OnLeaveMagicBarrier )
    ME_SCRIPT_WRAPPER( OnInMagicBarrier )
    ME_SCRIPT_WRAPPER( AddEnclaveTheftCount )
}

namespace Enclave
{
    ME_SCRIPT_WRAPPER( NotifyEnclave )
    ME_SCRIPT_WRAPPER( ChangeEnclaveStatus )
    ME_SCRIPT_WRAPPER( MemorizeEnclaveCrime )
    ME_SCRIPT_WRAPPER( AddEnclaveTheftCount )
}

namespace Player_Interface
{
    ME_SCRIPT_WRAPPER( OnPlayerChanged )
    ME_SCRIPT_WRAPPER( OnPlayerGameKeyPressed )
    ME_SCRIPT_WRAPPER( OnPlayerMovement )
    ME_SCRIPT_WRAPPER( OnPlayerAction )
    ME_SCRIPT_WRAPPER( OnPlayerSecondaryAction )
    ME_SCRIPT_WRAPPER( OnPlayerWalk )
    ME_SCRIPT_WRAPPER( OnPlayerSneak )
    ME_SCRIPT_WRAPPER( OnPlayerJump )
    ME_SCRIPT_WRAPPER( OnPlayerSelectWeapon )
    ME_SCRIPT_WRAPPER( OnPlayerConfirm )
    ME_SCRIPT_WRAPPER( OnPlayerUseQuickSlot )
    ME_SCRIPT_WRAPPER( OnPlayerPotionQuickUse )
}

namespace Player_States
{
    ME_SCRIPT_WRAPPER( OnHUDHandleInput )
    ME_SCRIPT_WRAPPER( OnPlayerUseStack )
    ME_SCRIPT_WRAPPER( OnPlayerFryStack )
    ME_SCRIPT_WRAPPER( OnPlayerTransformStack )
    ME_SCRIPT_WRAPPER( OnPlayerSynthRecipe )
    ME_SCRIPT_WRAPPER( OnPlayerGetDamage )
    ME_SCRIPT_WRAPPER( GetQualityBonus )
    ME_SCRIPT_WRAPPER( OnWantsToSell )
    ME_SCRIPT_WRAPPER( OnPlayerCanTransfer )
    ME_SCRIPT_WRAPPER( OnPlayerGetGoldCost )
    ME_SCRIPT_WRAPPER( OnPlayerGetEquipBonus )
    ME_SCRIPT_WRAPPER( OnPlayerAssignStackKey )
    ME_SCRIPT_WRAPPER( PlayerOpenBook )
    ME_SCRIPT_WRAPPER( PlayerOpenDialog )
    ME_SCRIPT_WRAPPER( PlayerOpenInventory )
    ME_SCRIPT_WRAPPER( PlayerOpenLetter )
    ME_SCRIPT_WRAPPER( PlayerOpenLoot )
    ME_SCRIPT_WRAPPER( PlayerOpenMap )
    ME_SCRIPT_WRAPPER( PlayerOpenQuests )
    ME_SCRIPT_WRAPPER( PlayerOpenSkills )
    ME_SCRIPT_WRAPPER( PlayerOpenSpells )
    ME_SCRIPT_WRAPPER( PlayerOpenTrade )
    ME_SCRIPT_WRAPPER( PlayerOpenAlchemy )
    ME_SCRIPT_WRAPPER( PlayerOpenSmithing )
    ME_SCRIPT_WRAPPER( PlayerOpenPoison )
    ME_SCRIPT_WRAPPER( PlayerOpenBless )
    ME_SCRIPT_WRAPPER( PlayerOpenFry )
    ME_SCRIPT_WRAPPER( OnToggleQuickSlots )
    ME_SCRIPT_WRAPPER_BA( HasRecipes, gESkillCategory )
    ME_SCRIPT_WRAPPER_B( HasBladeWeapon )
    ME_SCRIPT_WRAPPER_B( CanOpen )
    ME_SCRIPT_WRAPPER( StartSayNothingToGet )
    ME_SCRIPT_WRAPPER( StartSayDoesntWork )
    ME_SCRIPT_WRAPPER( GeneratePickOreInventory )
    ME_SCRIPT_WRAPPER( PlayerSleep )
    ME_SCRIPT_WRAPPER( OB_Light )
    ME_SCRIPT_WRAPPER( OB_Medium )
    ME_SCRIPT_WRAPPER( OB_Heavy )
    ME_SCRIPT_WRAPPER( OB_Faring_Boulder )
    ME_SCRIPT_WRAPPER_B( IsBasket )
    ME_SCRIPT_WRAPPER( InventoryAssureStartupItems )
    ME_SCRIPT_WRAPPER( InventoryPopulate )
    ME_SCRIPT_WRAPPER( OnMagicHandleInput )
    ME_SCRIPT_WRAPPER( OnGetAimAngle )
    ME_SCRIPT_WRAPPER( Shoot )
}

namespace Routine_Tasks
{
    ME_SCRIPT_WRAPPER( GetAmbientAction )
    ME_SCRIPT_WRAPPER( HaveABreak )
}

namespace Routine_Commands
{
    ME_SCRIPT_WRAPPER( ContinueRoutine )
    ME_SCRIPT_WRAPPER_B( CanHealSelf )
    ME_SCRIPT_WRAPPER( SelectRoutineDestination )
    ME_SCRIPT_WRAPPER( SetCurrentDestinationPoint )
    ME_SCRIPT_WRAPPER( SendToArena )
    ME_SCRIPT_WRAPPER_B( CanJoinPlayerParty )
    ME_SCRIPT_WRAPPER( JoinPlayerParty )
    ME_SCRIPT_WRAPPER( DismissPlayerParty )
    ME_SCRIPT_WRAPPER( JoinPlayerMob )
    ME_SCRIPT_WRAPPER( DismissPlayerMob )
    ME_SCRIPT_WRAPPER( JoinPlayerSlavery )
    ME_SCRIPT_WRAPPER( WaitPlayerParty )
    ME_SCRIPT_WRAPPER( StartGuidePlayer )
    ME_SCRIPT_WRAPPER( StopGuidePlayer )
    ME_SCRIPT_WRAPPER( StartBringNPC )
    ME_SCRIPT_WRAPPER( StopBringNPC )
    ME_SCRIPT_WRAPPER( SelectRoutineTask )
}

namespace Routine_Decision
{
    ME_SCRIPT_WRAPPER( GetRoutineTime )
    ME_SCRIPT_WRAPPER( GetTravellingWalkMode )
    ME_SCRIPT_WRAPPER_B( IsFreeDestination )
}

namespace Engine_Callback
{
    ME_SCRIPT_WRAPPER( GetAniStateByAction )
    ME_SCRIPT_WRAPPER( GetCombatMoveLength )
    ME_SCRIPT_WRAPPER( GetDCCRadius )
    ME_SCRIPT_WRAPPER( GetFocusEntityPriority )
    ME_SCRIPT_WRAPPER_B( IsFirstPersonCameraAllowed )
    ME_SCRIPT_WRAPPER( OnCheatKill )
    ME_SCRIPT_WRAPPER( OnCheatDefeat )
    ME_SCRIPT_WRAPPER( OnDamage )
    ME_SCRIPT_WRAPPER( OnEnterArea )
    ME_SCRIPT_WRAPPER( OnEnterProcessingRange )
    ME_SCRIPT_WRAPPER( RefreshHitPoints )
    ME_SCRIPT_WRAPPER( RefreshWeaponry )
    ME_SCRIPT_WRAPPER( EquipWeaponry )
    ME_SCRIPT_WRAPPER( Respawn )
    ME_SCRIPT_WRAPPER( OnExitProcessingRange )
    ME_SCRIPT_WRAPPER( OnGameStartUp )
    ME_SCRIPT_WRAPPER( OnHit )
    ME_SCRIPT_WRAPPER( OnInit )
    ME_SCRIPT_WRAPPER( OnLeaveArea )
    ME_SCRIPT_WRAPPER( OnMovementModeChanged )
    ME_SCRIPT_WRAPPER( OnPlayerScriptFinished )
    ME_SCRIPT_WRAPPER( OnProcessRoutine )
    ME_SCRIPT_WRAPPER( OnResetPlayer )
    ME_SCRIPT_WRAPPER( OnReturnFromMenu )
    ME_SCRIPT_WRAPPER( OnTick )
    ME_SCRIPT_WRAPPER( OnExit_Gorn )
    ME_SCRIPT_WRAPPER( OnEnclaveSectorRefresh )
    ME_SCRIPT_WRAPPER( HandleMusicSituation )
    ME_SCRIPT_WRAPPER( OnCharacterTouchesCharacter )
    ME_SCRIPT_WRAPPER( OnCharacterTouchesInteractable )
    ME_SCRIPT_WRAPPER( OnTouchDamage )
    ME_SCRIPT_WRAPPER( DoLogicalDamage )
    ME_SCRIPT_WRAPPER( OnProjectileTouchsLevel )
    ME_SCRIPT_WRAPPER( OnItemTouchesLevel )
    ME_SCRIPT_WRAPPER( OnItemTouchesCharacter )
    ME_SCRIPT_WRAPPER( OnItemTouchesInteractable )
    ME_SCRIPT_WRAPPER( OnItemTouchesItem )
    ME_SCRIPT_WRAPPER( OnItemReceived )
    ME_SCRIPT_WRAPPER( OnTouchZone )
}

namespace Engine_States
{
    ME_SCRIPT_WRAPPER_B( HasGuardNews )
    ME_SCRIPT_WRAPPER_B( HasBossNews )
    ME_SCRIPT_WRAPPER_B( HasCrimeRefuse )
    ME_SCRIPT_WRAPPER_B( HasHealInfo )
    ME_SCRIPT_WRAPPER_B( HasLongTimeNoSeeInfo )
    ME_SCRIPT_WRAPPER_B( HasMasterThiefInfo )
}

namespace Script_Mod
{
    namespace Inventory
    {
        ME_SCRIPT_WRAPPER( OnItemConsumed )
    }
}
