#ifndef SCRIPT_H_INCLUDED
#define SCRIPT_H_INCLUDED

#include "Game.h"

#include "Script/ScriptEnum.h"

#include "Script/gs_propertymacros.h"

class Entity;
#include "Script/gs_effect.h"
#include "Script/gs_effectsystem.h"
#include "Script/gs_psinfoscriptcommand.h"
#include "Script/gs_template.h"
#include "Script/gs_gui2.h"
#include "Script/gs_gui.h"
#include "Script/gs_info.h"
#include "Script/gs_music.h"
#include "Script/gs_psaizone.h"
#include "Script/gs_psanchor.h"
#include "Script/gs_psanimation.h"
#include "Script/gs_psarena.h"
#include "Script/gs_psbook.h"
#include "Script/gs_pscamera.h"
#include "Script/gs_pscharactercontrol.h"
#include "Script/gs_pscharactermovement.h"
#include "Script/gs_psclock.h"
#include "Script/gs_pscollisionshape.h"
#include "Script/gs_psdamage.h"
#include "Script/gs_psdamagereceiver.h"
#include "Script/gs_psdialog.h"
#include "Script/gs_psdoor.h"
#include "Script/gs_pseffect.h"
#include "Script/gs_psenclave.h"
#include "Script/gs_psfocus.h"
#include "Script/gs_psinfomanager.h"
#include "Script/gs_psinteraction.h"
#include "Script/gs_psinventory.h"
#include "Script/gs_psitem.h"
#include "Script/gs_psletter.h"
#include "Script/gs_pslock.h"
#include "Script/gs_psmagic.h"
#include "Script/gs_psmap.h"
#include "Script/gs_psmover.h"
#include "Script/gs_psnavigation.h"
#include "Script/gs_psnpc.h"
#include "Script/gs_psparticle.h"
#include "Script/gs_psparty.h"
#include "Script/gs_psplayermemory.h"
#include "Script/gs_psprojectile.h"
#include "Script/gs_psquestmanager.h"
#include "Script/gs_psrecipe.h"
#include "Script/gs_psrigidbody.h"
#include "Script/gs_psroutine.h"
#include "Script/gs_psskill.h"
#include "Script/gs_psstatistics.h"
#include "Script/gs_psstrip.h"
#include "Script/gs_pstouchdamage.h"
#include "Script/gs_pstreasureset.h"
#include "Script/gs_pstrigger.h"

#include "Script/gs_world.h"

#include "Script/gs_entity.h"

#include "Script/gs_psitemwrapper.h"

#include "Script/gs_scriptmacros.h"
#include "Script/gs_scriptargs.h"

#endif